modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://piglinmine.com/"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

# -------- Dependencies --------

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

# JEI required client-side — all our mixins target JEI internal classes.
# Server-side this mod is a no-op.
[[dependencies."${mod_id}"]]
modId = "jei"
mandatory = true
versionRange = "[15.0.0,)"
ordering = "AFTER"
side = "CLIENT"
